src/Entity/Logboek.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LogboekRepository")
 */
class Logboek
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $cover_letter;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="logboeks")
     * @ORM\JoinColumn(nullable=false)
     */
    private $driver;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Truck", inversedBy="logboeks")
     * @ORM\JoinColumn(nullable=false)
     */
    private $truck;

    /**
     * @ORM\Column(type="integer")
     */
    private $totalm3;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $load_location;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $time_departure;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $destination;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $event;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="user_id")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCoverLetter(): ?string
    {
        return $this->cover_letter;
    }

    public function setCoverLetter(string $cover_letter): self
    {
        $this->cover_letter = $cover_letter;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getDriver(): ?user
    {
        return $this->driver;
    }

    public function setDriver(?user $driver): self
    {
        $this->driver = $driver;

        return $this;
    }

    public function getTruck(): ?truck
    {
        return $this->truck;
    }

    public function setTruck(?truck $truck): self
    {
        $this->truck = $truck;

        return $this;
    }

    public function getTotalm3(): ?int
    {
        return $this->totalm3;
    }

    public function setTotalm3(int $totalm3): self
    {
        $this->totalm3 = $totalm3;

        return $this;
    }

    public function getLoadLocation(): ?string
    {
        return $this->load_location;
    }

    public function setLoadLocation(string $load_location): self
    {
        $this->load_location = $load_location;

        return $this;
    }

    public function getTimeDeparture(): ?string
    {
        return $this->time_departure;
    }

    public function setTimeDeparture(string $time_departure): self
    {
        $this->time_departure = $time_departure;

        return $this;
    }

    public function getDestination(): ?string
    {
        return $this->destination;
    }

    public function setDestination(string $destination): self
    {
        $this->destination = $destination;

        return $this;
    }

    public function getEvent(): ?string
    {
        return $this->event;
    }

    public function setEvent(string $event): self
    {
        $this->event = $event;

        return $this;
    }

    public function getUserId(): ?user
    {
        return $this->user_id;
    }

    public function setUserId(?user $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }
}

src/Form/LogboekType.php
<?php

namespace App\Form;

use App\Entity\Logboek;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LogboekType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('cover_letter')
            ->add('date')
            ->add('totalm3')
            ->add('load_location')
            ->add('time_departure')
            ->add('destination')
            ->add('event')
            ->add('driver')
            ->add('truck')
            ->add('user_id')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Logboek::class,
        ]);
    }
}

src/Controller/LogboekController.php
<?php

namespace App\Controller;

use App\Entity\Logboek;
use App\Form\LogboekType;
use App\Repository\LogboekRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/logboek")
 */
class LogboekController extends AbstractController
{
    /**
     * @Route("/", name="logboek_index", methods={"GET"})
     */
    public function index(LogboekRepository $logboekRepository): Response
    {
        return $this->render('logboek/index.html.twig', [
            'logboeks' => $logboekRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="logboek_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        if ($this->get('security.authorization_checker')->isGranted('ROLE_CHAUFFEUR', 'ROLE_ADMIN')) {
        throw $this->createAccessDeniedException('Access Denied.');
        }
        else {

        $logboek = new Logboek();
        $form = $this->createForm(LogboekType::class, $logboek);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($logboek);
            $entityManager->flush();

            return $this->redirectToRoute('logboek_index');
        }

        return $this->render('logboek/new.html.twig', [
            'logboek' => $logboek,
            'form' => $form->createView(),
        ]);
    }}

    /**
     * @Route("/{id}", name="logboek_show", methods={"GET"})
     */
    public function show(Logboek $logboek): Response
    {
        return $this->render('logboek/show.html.twig', [
            'logboek' => $logboek,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="logboek_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Logboek $logboek): Response
    {
        $form = $this->createForm(LogboekType::class, $logboek);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('logboek_index', [
                'id' => $logboek->getId(),
            ]);
    }

        return $this->render('logboek/edit.html.twig', [
            'logboek' => $logboek,
            'form' => $form->createView(),
        ]);
    }
    /**
     * @Route("/{id}", name="logboek_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Logboek $logboek): Response
    {
        if ($this->isCsrfTokenValid('delete'.$logboek->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($logboek);
            $entityManager->flush();
        }

        return $this->redirectToRoute('logboek_index');
    }
}

templates/logboek/_delete_form.html.twig
<form method="post" action="{{ path('logboek_delete', {'id': logboek.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ logboek.id) }}">
    <button class="btn">Delete</button>
</form>

templates/logboek/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/logboek/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Logboek{% endblock %}

{% block body %}
        <h1>Edit Logboek</h1>

    {{ include('logboek/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('logboek_index') }}">back to list</a>

    {{ include('logboek/_delete_form.html.twig') }}
{% endblock %}

templates/logboek/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Logboek index{% endblock %}

{% block body %}
    <h1>Logboek index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Cover_letter</th>
                <th>Date</th>
                <th>Totalm3</th>
                <th>Load_location</th>
                <th>Time_departure</th>
                <th>Destination</th>
                <th>Event</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for logboek in logboeks %}
            <tr>
                <td>{{ logboek.id }}</td>
                <td>{{ logboek.coverLetter }}</td>
                <td>{{ logboek.date ? logboek.date|date('Y-m-d') : '' }}</td>
                <td>{{ logboek.totalm3 }}</td>
                <td>{{ logboek.loadLocation }}</td>
                <td>{{ logboek.timeDeparture }}</td>
                <td>{{ logboek.destination }}</td>
                <td>{{ logboek.event }}</td>
                <td>
                    <a href="{{ path('logboek_show', {'id': logboek.id}) }}">show</a>
                    {% if is_granted('ROLE_CHAUFFEUR') or is_granted('ROLE_SUPER_ADMIN') %}
                        <a href="{{ path('logboek_edit', {'id': logboek.id}) }}">edit</a>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('logboek_new') }}">Create new</a>
{% endblock %}

templates/logboek/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Logboek{% endblock %}

{% block body %}
    <h1>Create new Logboek</h1>

    {{ include('logboek/_form.html.twig') }}

    <a href="{{ path('logboek_index') }}">back to list</a>
{% endblock %}

templates/logboek/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Logboek{% endblock %}

{% block body %}
    <h1>Logboek</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ logboek.id }}</td>
            </tr>
            <tr>
                <th>Cover_letter</th>
                <td>{{ logboek.coverLetter }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ logboek.date ? logboek.date|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Totalm3</th>
                <td>{{ logboek.totalm3 }}</td>
            </tr>
            <tr>
                <th>Load_location</th>
                <td>{{ logboek.loadLocation }}</td>
            </tr>
            <tr>
                <th>Time_departure</th>
                <td>{{ logboek.timeDeparture }}</td>
            </tr>
            <tr>
                <th>Destination</th>
                <td>{{ logboek.destination }}</td>
            </tr>
            <tr>
                <th>Event</th>
                <td>{{ logboek.event }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('logboek_index') }}">back to list</a>

    <a href="{{ path('logboek_edit', {'id': logboek.id}) }}">edit</a>

    {{ include('logboek/_delete_form.html.twig') }}
{% endblock %}