src/Entity/Truck.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TruckRepository")
 */
class Truck
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $drivers_lisence;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $merk;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Logboek", mappedBy="truck")
     */
    private $logboeks;

    public function __toString()
    {
        return $this->drivers_lisence;
    }

    public function __construct()
    {
        $this->logboeks = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDriversLisence(): ?string
    {
        return $this->drivers_lisence;
    }

    public function setDriversLisence(string $drivers_lisence): self
    {
        $this->drivers_lisence = $drivers_lisence;

        return $this;
    }

    public function getMerk(): ?string
    {
        return $this->merk;
    }

    public function setMerk(string $merk): self
    {
        $this->merk = $merk;

        return $this;
    }

    /**
     * @return Collection|Logboek[]
     */
    public function getLogboeks(): Collection
    {
        return $this->logboeks;
    }

    public function addLogboek(Logboek $logboek): self
    {
        if (!$this->logboeks->contains($logboek)) {
            $this->logboeks[] = $logboek;
            $logboek->setTruck($this);
        }

        return $this;
    }

    public function removeLogboek(Logboek $logboek): self
    {
        if ($this->logboeks->contains($logboek)) {
            $this->logboeks->removeElement($logboek);
            // set the owning side to null (unless already changed)
            if ($logboek->getTruck() === $this) {
                $logboek->setTruck(null);
            }
        }

        return $this;
    }
}

src/Form/TruckType.php
<?php

namespace App\Form;

use App\Entity\Truck;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TruckType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('drivers_lisence')
            ->add('merk')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Truck::class,
        ]);
    }
}

src/Controller/TruckController.php
<?php

namespace App\Controller;

use App\Entity\Truck;
use App\Form\TruckType;
use App\Repository\TruckRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/truck")
 */
class TruckController extends AbstractController
{
    /**
     * @Route("/", name="truck_index", methods={"GET"})
     */
    public function index(TruckRepository $truckRepository): Response
    {
        return $this->render('truck/index.html.twig', [
            'trucks' => $truckRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="truck_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        if ($this->get('security.authorization_checker')->isGranted('ROLE_CHAUFFEUR', 'ROLE_ADMIN')) {
            throw $this->createAccessDeniedException('Access Denied.');
        }
        $truck = new Truck();
        $form = $this->createForm(TruckType::class, $truck);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($truck);
            $entityManager->flush();

            return $this->redirectToRoute('truck_index');
        }

        return $this->render('truck/new.html.twig', [
            'truck' => $truck,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="truck_show", methods={"GET"})
     */
    public function show(Truck $truck): Response
    {
        return $this->render('truck/show.html.twig', [
            'truck' => $truck,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="truck_edit", methods={"GET","POST"})
     */

    public function edit(Request $request, Truck $truck): Response
    {
        if ($this->get('security.authorization_checker')->isGranted('ROLE_CHAUFFEUR', 'ROLE_ADMIN')) {
            throw $this->createAccessDeniedException('Access Denied.');
        }
        $form = $this->createForm(TruckType::class, $truck);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('truck_index', [
                'id' => $truck->getId(),
            ]);
        }

        return $this->render('truck/edit.html.twig', [
            'truck' => $truck,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="truck_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Truck $truck): Response
    {
        if ($this->isCsrfTokenValid('delete'.$truck->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($truck);
            $entityManager->flush();
        }

        return $this->redirectToRoute('truck_index');
    }
}

templates/truck/_delete_form.html.twig
<form method="post" action="{{ path('truck_delete', {'id': truck.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ truck.id) }}">
    <button class="btn">Delete</button>
</form>

templates/truck/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/truck/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Truck{% endblock %}

{% block body %}
    <h1>Edit Truck</h1>

    {{ include('truck/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('truck_index') }}">back to list</a>

    {{ include('truck/_delete_form.html.twig') }}
{% endblock %}

templates/truck/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Truck index{% endblock %}

{% block body %}
    <h1>Truck index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Drivers_lisence</th>
                <th>Merk</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for truck in trucks %}
            <tr>
                <td>{{ truck.id }}</td>
                <td>{{ truck.driversLisence }}</td>
                <td>{{ truck.merk }}</td>
                <td>
                    <a href="{{ path('truck_show', {'id': truck.id}) }}">show</a>
                    <a href="{{ path('truck_edit', {'id': truck.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('truck_new') }}">Create new</a>
{% endblock %}

templates/truck/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Truck{% endblock %}

{% block body %}
    <h1>Create new Truck</h1>

    {{ include('truck/_form.html.twig') }}

    <a href="{{ path('truck_index') }}">back to list</a>
{% endblock %}

templates/truck/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Truck{% endblock %}

{% block body %}
    <h1>Truck</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ truck.id }}</td>
            </tr>
            <tr>
                <th>Drivers_lisence</th>
                <td>{{ truck.driversLisence }}</td>
            </tr>
            <tr>
                <th>Merk</th>
                <td>{{ truck.merk }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('truck_index') }}">back to list</a>

    <a href="{{ path('truck_edit', {'id': truck.id}) }}">edit</a>

    {{ include('truck/_delete_form.html.twig') }}
{% endblock %}